//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.resumeparsing.com/", ConfigurationName="ServiceReference1.ParsingServiceSoap")]
    public interface ParsingServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseResume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.ParseResumeResponse> ParseResumeAsync(ServiceReference1.ParseResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.GetAccountInfoResponse> GetAccountInfoAsync(ServiceReference1.GetAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseJobOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.ParseJobOrderResponse> ParseJobOrderAsync(ServiceReference1.ParseJobOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/SetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.SetDataResponse> SetDataAsync(ServiceReference1.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.GetDataResponse> GetDataAsync(ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ListData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.ListDataResponse> ListDataAsync(ServiceReference1.ListDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/DeleteData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.DeleteDataResponse> DeleteDataAsync(ServiceReference1.DeleteDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/NormalizeResume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ServiceReference1.NormalizeResumeResponse> NormalizeResumeAsync(ServiceReference1.NormalizeResumeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeRequest
    {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private string configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        private System.Nullable<bool> outputCandidateImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileBytes
        {
            get
            {
                return this.fileBytesField;
            }
            set
            {
                this.fileBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileText
        {
            get
            {
                return this.fileTextField;
            }
            set
            {
                this.fileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> OutputXmlDoc
        {
            get
            {
                return this.outputXmlDocField;
            }
            set
            {
                this.outputXmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> OutputHtml
        {
            get
            {
                return this.outputHtmlField;
            }
            set
            {
                this.outputHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> OutputRtf
        {
            get
            {
                return this.outputRtfField;
            }
            set
            {
                this.outputRtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> OutputWordXml
        {
            get
            {
                return this.outputWordXmlField;
            }
            set
            {
                this.outputWordXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RevisionDate
        {
            get
            {
                return this.revisionDateField;
            }
            set
            {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ParserVersion
        {
            get
            {
                return this.parserVersionField;
            }
            set
            {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SkillsData
        {
            get
            {
                return this.skillsDataField;
            }
            set
            {
                this.skillsDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NormalizerData
        {
            get
            {
                return this.normalizerDataField;
            }
            set
            {
                this.normalizerDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> OutputPdf
        {
            get
            {
                return this.outputPdfField;
            }
            set
            {
                this.outputPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> OutputCandidateImage
        {
            get
            {
                return this.outputCandidateImageField;
            }
            set
            {
                this.outputCandidateImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class Data
    {
        
        private string keyField;
        
        private string nameField;
        
        private string typeField;
        
        private string cultureField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseResponse
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeResponse : BaseResponse
    {
        
        private string xmlField;
        
        private int creditsRemainingField;
        
        private string normalizerVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreditsRemaining
        {
            get
            {
                return this.creditsRemainingField;
            }
            set
            {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NormalizerVersion
        {
            get
            {
                return this.normalizerVersionField;
            }
            set
            {
                this.normalizerVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataResponse : BaseResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataResponse : BaseResponse
    {
        
        private Data[] dataListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Data[] DataList
        {
            get
            {
                return this.dataListField;
            }
            set
            {
                this.dataListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataResponse : BaseResponse
    {
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ContentBytes
        {
            get
            {
                return this.contentBytesField;
            }
            set
            {
                this.contentBytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataResponse : BaseResponse
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseRequest
    {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeRequest : BaseRequest
    {
        
        private string xmlField;
        
        private string normalizerDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NormalizerData
        {
            get
            {
                return this.normalizerDataField;
            }
            set
            {
                this.normalizerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataRequest : BaseRequest
    {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataRequest : BaseRequest
    {
        
        private string typeField;
        
        private string cultureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataRequest : BaseRequest
    {
        
        private string nameField;
        
        private string cultureField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataRequest : BaseRequest
    {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] ContentBytes
        {
            get
            {
                return this.contentBytesField;
            }
            set
            {
                this.contentBytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderResponse
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.Linq.XElement xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextCode
        {
            get
            {
                return this.textCodeField;
            }
            set
            {
                this.textCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Xml.Linq.XElement XmlDoc
        {
            get
            {
                return this.xmlDocField;
            }
            set
            {
                this.xmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Html
        {
            get
            {
                return this.htmlField;
            }
            set
            {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HtmlCode
        {
            get
            {
                return this.htmlCodeField;
            }
            set
            {
                this.htmlCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Rtf
        {
            get
            {
                return this.rtfField;
            }
            set
            {
                this.rtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RtfCode
        {
            get
            {
                return this.rtfCodeField;
            }
            set
            {
                this.rtfCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WordXml
        {
            get
            {
                return this.wordXmlField;
            }
            set
            {
                this.wordXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string WordXmlCode
        {
            get
            {
                return this.wordXmlCodeField;
            }
            set
            {
                this.wordXmlCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int CreditsRemaining
        {
            get
            {
                return this.creditsRemainingField;
            }
            set
            {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ParserVersion
        {
            get
            {
                return this.parserVersionField;
            }
            set
            {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=17)]
        public byte[] Pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PdfCode
        {
            get
            {
                return this.pdfCodeField;
            }
            set
            {
                this.pdfCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderConfiguration
    {
        
        private string countryCodeField;
        
        private string languageField;
        
        private string knownTypeField;
        
        private bool includeRecruitingTermsField;
        
        private bool includeSupplementalTextField;
        
        private bool preferShorterJobTitlesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KnownType
        {
            get
            {
                return this.knownTypeField;
            }
            set
            {
                this.knownTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IncludeRecruitingTerms
        {
            get
            {
                return this.includeRecruitingTermsField;
            }
            set
            {
                this.includeRecruitingTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IncludeSupplementalText
        {
            get
            {
                return this.includeSupplementalTextField;
            }
            set
            {
                this.includeSupplementalTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool PreferShorterJobTitles
        {
            get
            {
                return this.preferShorterJobTitlesField;
            }
            set
            {
                this.preferShorterJobTitlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderRequest
    {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private ParseJobOrderConfiguration configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileBytes
        {
            get
            {
                return this.fileBytesField;
            }
            set
            {
                this.fileBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileText
        {
            get
            {
                return this.fileTextField;
            }
            set
            {
                this.fileTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ParseJobOrderConfiguration Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> OutputXmlDoc
        {
            get
            {
                return this.outputXmlDocField;
            }
            set
            {
                this.outputXmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> OutputHtml
        {
            get
            {
                return this.outputHtmlField;
            }
            set
            {
                this.outputHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> OutputRtf
        {
            get
            {
                return this.outputRtfField;
            }
            set
            {
                this.outputRtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> OutputWordXml
        {
            get
            {
                return this.outputWordXmlField;
            }
            set
            {
                this.outputWordXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RevisionDate
        {
            get
            {
                return this.revisionDateField;
            }
            set
            {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ParserVersion
        {
            get
            {
                return this.parserVersionField;
            }
            set
            {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SkillsData
        {
            get
            {
                return this.skillsDataField;
            }
            set
            {
                this.skillsDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NormalizerData
        {
            get
            {
                return this.normalizerDataField;
            }
            set
            {
                this.normalizerDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> OutputPdf
        {
            get
            {
                return this.outputPdfField;
            }
            set
            {
                this.outputPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoResponse
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private int creditsUsedField;
        
        private int creditsRemainingField;
        
        private string expirationDateField;
        
        private int maximumConcurrentRequestsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CreditsUsed
        {
            get
            {
                return this.creditsUsedField;
            }
            set
            {
                this.creditsUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int CreditsRemaining
        {
            get
            {
                return this.creditsRemainingField;
            }
            set
            {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int MaximumConcurrentRequests
        {
            get
            {
                return this.maximumConcurrentRequestsField;
            }
            set
            {
                this.maximumConcurrentRequestsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoRequest
    {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeResponse
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.Linq.XElement xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        private byte[] candidateImageField;
        
        private string candidateImageExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextCode
        {
            get
            {
                return this.textCodeField;
            }
            set
            {
                this.textCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Xml.Linq.XElement XmlDoc
        {
            get
            {
                return this.xmlDocField;
            }
            set
            {
                this.xmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Html
        {
            get
            {
                return this.htmlField;
            }
            set
            {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HtmlCode
        {
            get
            {
                return this.htmlCodeField;
            }
            set
            {
                this.htmlCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Rtf
        {
            get
            {
                return this.rtfField;
            }
            set
            {
                this.rtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RtfCode
        {
            get
            {
                return this.rtfCodeField;
            }
            set
            {
                this.rtfCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WordXml
        {
            get
            {
                return this.wordXmlField;
            }
            set
            {
                this.wordXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string WordXmlCode
        {
            get
            {
                return this.wordXmlCodeField;
            }
            set
            {
                this.wordXmlCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int CreditsRemaining
        {
            get
            {
                return this.creditsRemainingField;
            }
            set
            {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ParserVersion
        {
            get
            {
                return this.parserVersionField;
            }
            set
            {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=17)]
        public byte[] Pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PdfCode
        {
            get
            {
                return this.pdfCodeField;
            }
            set
            {
                this.pdfCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=19)]
        public byte[] CandidateImage
        {
            get
            {
                return this.candidateImageField;
            }
            set
            {
                this.candidateImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CandidateImageExtension
        {
            get
            {
                return this.candidateImageExtensionField;
            }
            set
            {
                this.candidateImageExtensionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface ParsingServiceSoapChannel : ServiceReference1.ParsingServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class ParsingServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.ParsingServiceSoap>, ServiceReference1.ParsingServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ParsingServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ParsingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ParsingServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParsingServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ParsingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParsingServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ParsingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParsingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ParseResumeResponse> ParseResumeAsync(ServiceReference1.ParseResumeRequest request)
        {
            return base.Channel.ParseResumeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAccountInfoResponse> GetAccountInfoAsync(ServiceReference1.GetAccountInfoRequest request)
        {
            return base.Channel.GetAccountInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ParseJobOrderResponse> ParseJobOrderAsync(ServiceReference1.ParseJobOrderRequest request)
        {
            return base.Channel.ParseJobOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetDataResponse> SetDataAsync(ServiceReference1.SetDataRequest request)
        {
            return base.Channel.SetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataResponse> GetDataAsync(ServiceReference1.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListDataResponse> ListDataAsync(ServiceReference1.ListDataRequest request)
        {
            return base.Channel.ListDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteDataResponse> DeleteDataAsync(ServiceReference1.DeleteDataRequest request)
        {
            return base.Channel.DeleteDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.NormalizeResumeResponse> NormalizeResumeAsync(ServiceReference1.NormalizeResumeRequest request)
        {
            return base.Channel.NormalizeResumeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParsingServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ParsingServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParsingServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://eu-services.resumeparsing.com/ParsingService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ParsingServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://eu-services.resumeparsing.com/ParsingService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ParsingServiceSoap,
            
            ParsingServiceSoap12,
        }
    }
}
