//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovrenCVNETFull.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.resumeparsing.com/", ConfigurationName="ServiceReference1.ParsingServiceSoap")]
    public interface ParsingServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseResume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.ParseResumeResponse ParseResume(SovrenCVNETFull.ServiceReference1.ParseResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseResume", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ParseResumeResponse> ParseResumeAsync(SovrenCVNETFull.ServiceReference1.ParseResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.GetAccountInfoResponse GetAccountInfo(SovrenCVNETFull.ServiceReference1.GetAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetAccountInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.GetAccountInfoResponse> GetAccountInfoAsync(SovrenCVNETFull.ServiceReference1.GetAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseJobOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.ParseJobOrderResponse ParseJobOrder(SovrenCVNETFull.ServiceReference1.ParseJobOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseJobOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ParseJobOrderResponse> ParseJobOrderAsync(SovrenCVNETFull.ServiceReference1.ParseJobOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/SetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.SetDataResponse SetData(SovrenCVNETFull.ServiceReference1.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/SetData", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.SetDataResponse> SetDataAsync(SovrenCVNETFull.ServiceReference1.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.GetDataResponse GetData(SovrenCVNETFull.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.GetDataResponse> GetDataAsync(SovrenCVNETFull.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ListData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.ListDataResponse ListData(SovrenCVNETFull.ServiceReference1.ListDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ListData", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ListDataResponse> ListDataAsync(SovrenCVNETFull.ServiceReference1.ListDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/DeleteData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.DeleteDataResponse DeleteData(SovrenCVNETFull.ServiceReference1.DeleteDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/DeleteData", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.DeleteDataResponse> DeleteDataAsync(SovrenCVNETFull.ServiceReference1.DeleteDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/NormalizeResume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        SovrenCVNETFull.ServiceReference1.NormalizeResumeResponse NormalizeResume(SovrenCVNETFull.ServiceReference1.NormalizeResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/NormalizeResume", ReplyAction="*")]
        System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.NormalizeResumeResponse> NormalizeResumeAsync(SovrenCVNETFull.ServiceReference1.NormalizeResumeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private string configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        private System.Nullable<bool> outputCandidateImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                this.fileBytesField = value;
                this.RaisePropertyChanged("FileBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileText {
            get {
                return this.fileTextField;
            }
            set {
                this.fileTextField = value;
                this.RaisePropertyChanged("FileText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> OutputXmlDoc {
            get {
                return this.outputXmlDocField;
            }
            set {
                this.outputXmlDocField = value;
                this.RaisePropertyChanged("OutputXmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> OutputHtml {
            get {
                return this.outputHtmlField;
            }
            set {
                this.outputHtmlField = value;
                this.RaisePropertyChanged("OutputHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> OutputRtf {
            get {
                return this.outputRtfField;
            }
            set {
                this.outputRtfField = value;
                this.RaisePropertyChanged("OutputRtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> OutputWordXml {
            get {
                return this.outputWordXmlField;
            }
            set {
                this.outputWordXmlField = value;
                this.RaisePropertyChanged("OutputWordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
                this.RaisePropertyChanged("RevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SkillsData {
            get {
                return this.skillsDataField;
            }
            set {
                this.skillsDataField = value;
                this.RaisePropertyChanged("SkillsData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
                this.RaisePropertyChanged("NormalizerData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> OutputPdf {
            get {
                return this.outputPdfField;
            }
            set {
                this.outputPdfField = value;
                this.RaisePropertyChanged("OutputPdf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> OutputCandidateImage {
            get {
                return this.outputCandidateImageField;
            }
            set {
                this.outputCandidateImageField = value;
                this.RaisePropertyChanged("OutputCandidateImage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string nameField;
        
        private string typeField;
        
        private string cultureField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeResponse : BaseResponse {
        
        private string xmlField;
        
        private int creditsRemainingField;
        
        private string normalizerVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("Xml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NormalizerVersion {
            get {
                return this.normalizerVersionField;
            }
            set {
                this.normalizerVersionField = value;
                this.RaisePropertyChanged("NormalizerVersion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataResponse : BaseResponse {
        
        private Data[] dataListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Data[] DataList {
            get {
                return this.dataListField;
            }
            set {
                this.dataListField = value;
                this.RaisePropertyChanged("DataList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataResponse : BaseResponse {
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ContentBytes {
            get {
                return this.contentBytesField;
            }
            set {
                this.contentBytesField = value;
                this.RaisePropertyChanged("ContentBytes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeRequest : BaseRequest {
        
        private string xmlField;
        
        private string normalizerDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("Xml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
                this.RaisePropertyChanged("NormalizerData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataRequest : BaseRequest {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataRequest : BaseRequest {
        
        private string typeField;
        
        private string cultureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataRequest : BaseRequest {
        
        private string nameField;
        
        private string cultureField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataRequest : BaseRequest {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] ContentBytes {
            get {
                return this.contentBytesField;
            }
            set {
                this.contentBytesField = value;
                this.RaisePropertyChanged("ContentBytes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.XmlNode xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextCode {
            get {
                return this.textCodeField;
            }
            set {
                this.textCodeField = value;
                this.RaisePropertyChanged("TextCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("Xml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Xml.XmlNode XmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
                this.RaisePropertyChanged("XmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
                this.RaisePropertyChanged("Html");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HtmlCode {
            get {
                return this.htmlCodeField;
            }
            set {
                this.htmlCodeField = value;
                this.RaisePropertyChanged("HtmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Rtf {
            get {
                return this.rtfField;
            }
            set {
                this.rtfField = value;
                this.RaisePropertyChanged("Rtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RtfCode {
            get {
                return this.rtfCodeField;
            }
            set {
                this.rtfCodeField = value;
                this.RaisePropertyChanged("RtfCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WordXml {
            get {
                return this.wordXmlField;
            }
            set {
                this.wordXmlField = value;
                this.RaisePropertyChanged("WordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string WordXmlCode {
            get {
                return this.wordXmlCodeField;
            }
            set {
                this.wordXmlCodeField = value;
                this.RaisePropertyChanged("WordXmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
                this.RaisePropertyChanged("FileExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=17)]
        public byte[] Pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("Pdf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PdfCode {
            get {
                return this.pdfCodeField;
            }
            set {
                this.pdfCodeField = value;
                this.RaisePropertyChanged("PdfCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string languageField;
        
        private string knownTypeField;
        
        private bool includeRecruitingTermsField;
        
        private bool includeSupplementalTextField;
        
        private bool preferShorterJobTitlesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KnownType {
            get {
                return this.knownTypeField;
            }
            set {
                this.knownTypeField = value;
                this.RaisePropertyChanged("KnownType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IncludeRecruitingTerms {
            get {
                return this.includeRecruitingTermsField;
            }
            set {
                this.includeRecruitingTermsField = value;
                this.RaisePropertyChanged("IncludeRecruitingTerms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IncludeSupplementalText {
            get {
                return this.includeSupplementalTextField;
            }
            set {
                this.includeSupplementalTextField = value;
                this.RaisePropertyChanged("IncludeSupplementalText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool PreferShorterJobTitles {
            get {
                return this.preferShorterJobTitlesField;
            }
            set {
                this.preferShorterJobTitlesField = value;
                this.RaisePropertyChanged("PreferShorterJobTitles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private ParseJobOrderConfiguration configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                this.fileBytesField = value;
                this.RaisePropertyChanged("FileBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileText {
            get {
                return this.fileTextField;
            }
            set {
                this.fileTextField = value;
                this.RaisePropertyChanged("FileText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ParseJobOrderConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> OutputXmlDoc {
            get {
                return this.outputXmlDocField;
            }
            set {
                this.outputXmlDocField = value;
                this.RaisePropertyChanged("OutputXmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> OutputHtml {
            get {
                return this.outputHtmlField;
            }
            set {
                this.outputHtmlField = value;
                this.RaisePropertyChanged("OutputHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> OutputRtf {
            get {
                return this.outputRtfField;
            }
            set {
                this.outputRtfField = value;
                this.RaisePropertyChanged("OutputRtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> OutputWordXml {
            get {
                return this.outputWordXmlField;
            }
            set {
                this.outputWordXmlField = value;
                this.RaisePropertyChanged("OutputWordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
                this.RaisePropertyChanged("RevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SkillsData {
            get {
                return this.skillsDataField;
            }
            set {
                this.skillsDataField = value;
                this.RaisePropertyChanged("SkillsData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
                this.RaisePropertyChanged("NormalizerData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> OutputPdf {
            get {
                return this.outputPdfField;
            }
            set {
                this.outputPdfField = value;
                this.RaisePropertyChanged("OutputPdf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private int creditsUsedField;
        
        private int creditsRemainingField;
        
        private string expirationDateField;
        
        private int maximumConcurrentRequestsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CreditsUsed {
            get {
                return this.creditsUsedField;
            }
            set {
                this.creditsUsedField = value;
                this.RaisePropertyChanged("CreditsUsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int MaximumConcurrentRequests {
            get {
                return this.maximumConcurrentRequestsField;
            }
            set {
                this.maximumConcurrentRequestsField = value;
                this.RaisePropertyChanged("MaximumConcurrentRequests");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.XmlNode xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        private byte[] candidateImageField;
        
        private string candidateImageExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextCode {
            get {
                return this.textCodeField;
            }
            set {
                this.textCodeField = value;
                this.RaisePropertyChanged("TextCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("Xml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Xml.XmlNode XmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
                this.RaisePropertyChanged("XmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
                this.RaisePropertyChanged("Html");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HtmlCode {
            get {
                return this.htmlCodeField;
            }
            set {
                this.htmlCodeField = value;
                this.RaisePropertyChanged("HtmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Rtf {
            get {
                return this.rtfField;
            }
            set {
                this.rtfField = value;
                this.RaisePropertyChanged("Rtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RtfCode {
            get {
                return this.rtfCodeField;
            }
            set {
                this.rtfCodeField = value;
                this.RaisePropertyChanged("RtfCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WordXml {
            get {
                return this.wordXmlField;
            }
            set {
                this.wordXmlField = value;
                this.RaisePropertyChanged("WordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string WordXmlCode {
            get {
                return this.wordXmlCodeField;
            }
            set {
                this.wordXmlCodeField = value;
                this.RaisePropertyChanged("WordXmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
                this.RaisePropertyChanged("FileExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=17)]
        public byte[] Pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("Pdf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PdfCode {
            get {
                return this.pdfCodeField;
            }
            set {
                this.pdfCodeField = value;
                this.RaisePropertyChanged("PdfCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=19)]
        public byte[] CandidateImage {
            get {
                return this.candidateImageField;
            }
            set {
                this.candidateImageField = value;
                this.RaisePropertyChanged("CandidateImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CandidateImageExtension {
            get {
                return this.candidateImageExtensionField;
            }
            set {
                this.candidateImageExtensionField = value;
                this.RaisePropertyChanged("CandidateImageExtension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParsingServiceSoapChannel : SovrenCVNETFull.ServiceReference1.ParsingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParsingServiceSoapClient : System.ServiceModel.ClientBase<SovrenCVNETFull.ServiceReference1.ParsingServiceSoap>, SovrenCVNETFull.ServiceReference1.ParsingServiceSoap {
        
        public ParsingServiceSoapClient() {
        }
        
        public ParsingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParsingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SovrenCVNETFull.ServiceReference1.ParseResumeResponse ParseResume(SovrenCVNETFull.ServiceReference1.ParseResumeRequest request) {
            return base.Channel.ParseResume(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ParseResumeResponse> ParseResumeAsync(SovrenCVNETFull.ServiceReference1.ParseResumeRequest request) {
            return base.Channel.ParseResumeAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.GetAccountInfoResponse GetAccountInfo(SovrenCVNETFull.ServiceReference1.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfo(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.GetAccountInfoResponse> GetAccountInfoAsync(SovrenCVNETFull.ServiceReference1.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfoAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.ParseJobOrderResponse ParseJobOrder(SovrenCVNETFull.ServiceReference1.ParseJobOrderRequest request) {
            return base.Channel.ParseJobOrder(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ParseJobOrderResponse> ParseJobOrderAsync(SovrenCVNETFull.ServiceReference1.ParseJobOrderRequest request) {
            return base.Channel.ParseJobOrderAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.SetDataResponse SetData(SovrenCVNETFull.ServiceReference1.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.SetDataResponse> SetDataAsync(SovrenCVNETFull.ServiceReference1.SetDataRequest request) {
            return base.Channel.SetDataAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.GetDataResponse GetData(SovrenCVNETFull.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.GetDataResponse> GetDataAsync(SovrenCVNETFull.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.ListDataResponse ListData(SovrenCVNETFull.ServiceReference1.ListDataRequest request) {
            return base.Channel.ListData(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.ListDataResponse> ListDataAsync(SovrenCVNETFull.ServiceReference1.ListDataRequest request) {
            return base.Channel.ListDataAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.DeleteDataResponse DeleteData(SovrenCVNETFull.ServiceReference1.DeleteDataRequest request) {
            return base.Channel.DeleteData(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.DeleteDataResponse> DeleteDataAsync(SovrenCVNETFull.ServiceReference1.DeleteDataRequest request) {
            return base.Channel.DeleteDataAsync(request);
        }
        
        public SovrenCVNETFull.ServiceReference1.NormalizeResumeResponse NormalizeResume(SovrenCVNETFull.ServiceReference1.NormalizeResumeRequest request) {
            return base.Channel.NormalizeResume(request);
        }
        
        public System.Threading.Tasks.Task<SovrenCVNETFull.ServiceReference1.NormalizeResumeResponse> NormalizeResumeAsync(SovrenCVNETFull.ServiceReference1.NormalizeResumeRequest request) {
            return base.Channel.NormalizeResumeAsync(request);
        }
    }
}
